apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: {{ .Values.producer.replicas }}
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
        version: v1
    spec:
      containers:
        - name: producer
          image: {{ include "ds-app.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.producer.port }}
          env:
            - name: Kafka__BootstrapServers
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: Kafka__Topic
              value: "{{ .Values.kafka.topic }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.producer.port }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.producer.port }}
